// <auto-generated />
using System;
using CariErinc.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CariErinc.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260314103156_IadeIptalEkle")]
    partial class IadeIptalEkle
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CariErinc.Models.Alis", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Aciklama")
                        .HasColumnType("text");

                    b.Property<decimal>("KalanBorc")
                        .HasColumnType("numeric");

                    b.Property<int>("OdemeTipi")
                        .HasColumnType("integer");

                    b.Property<decimal>("OdenenTutar")
                        .HasColumnType("numeric");

                    b.Property<bool>("OdenmeDurumu_Odendi")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("Tarih")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("TedarikciId")
                        .HasColumnType("integer");

                    b.Property<decimal>("ToplamTutar")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTime?>("VadeTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("TedarikciId");

                    b.ToTable("Alislar");
                });

            modelBuilder.Entity("CariErinc.Models.AlisDetay", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AlisId")
                        .HasColumnType("integer");

                    b.Property<decimal>("BirimFiyat")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<int>("KdvOrani")
                        .HasColumnType("integer");

                    b.Property<decimal>("KdvTutari")
                        .HasColumnType("numeric");

                    b.Property<int>("Miktar")
                        .HasColumnType("integer");

                    b.Property<int>("UrunId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AlisId");

                    b.HasIndex("UrunId");

                    b.ToTable("AlisDetaylari");
                });

            modelBuilder.Entity("CariErinc.Models.AlisOdeme", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Aciklama")
                        .HasColumnType("text");

                    b.Property<int>("AlisId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("OdemeTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("OdemeTutari")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("AlisId");

                    b.ToTable("AlisOdemeleri");
                });

            modelBuilder.Entity("CariErinc.Models.AuditLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Aciklama")
                        .HasColumnType("text");

                    b.Property<string>("EskiDeger")
                        .HasColumnType("text");

                    b.Property<string>("Islem")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("KayitId")
                        .HasColumnType("integer");

                    b.Property<string>("KullaniciAdi")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Tablo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("Tarih")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("YeniDeger")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("AuditLoglari");
                });

            modelBuilder.Entity("CariErinc.Models.GiderKategori", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("AktifMi")
                        .HasColumnType("boolean");

                    b.Property<bool>("SilinebilirMi")
                        .HasColumnType("boolean");

                    b.Property<int>("Tip")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("GiderKategoriler");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Ad = "Satış",
                            AktifMi = true,
                            SilinebilirMi = false,
                            Tip = 0
                        },
                        new
                        {
                            Id = 2,
                            Ad = "Veresiye Ödeme",
                            AktifMi = true,
                            SilinebilirMi = false,
                            Tip = 0
                        },
                        new
                        {
                            Id = 3,
                            Ad = "Alış",
                            AktifMi = true,
                            SilinebilirMi = false,
                            Tip = 1
                        },
                        new
                        {
                            Id = 4,
                            Ad = "Kira",
                            AktifMi = true,
                            SilinebilirMi = true,
                            Tip = 1
                        },
                        new
                        {
                            Id = 5,
                            Ad = "Fatura",
                            AktifMi = true,
                            SilinebilirMi = true,
                            Tip = 1
                        },
                        new
                        {
                            Id = 6,
                            Ad = "Maaş",
                            AktifMi = true,
                            SilinebilirMi = true,
                            Tip = 1
                        },
                        new
                        {
                            Id = 7,
                            Ad = "Diğer",
                            AktifMi = true,
                            SilinebilirMi = true,
                            Tip = 1
                        },
                        new
                        {
                            Id = 8,
                            Ad = "Satış İadesi",
                            AktifMi = true,
                            SilinebilirMi = false,
                            Tip = 1
                        },
                        new
                        {
                            Id = 9,
                            Ad = "Alış İadesi",
                            AktifMi = true,
                            SilinebilirMi = false,
                            Tip = 0
                        });
                });

            modelBuilder.Entity("CariErinc.Models.KasaHareket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Aciklama")
                        .HasColumnType("text");

                    b.Property<int?>("GiderKategoriId")
                        .HasColumnType("integer");

                    b.Property<int>("HareketTipi")
                        .HasColumnType("integer");

                    b.Property<string>("Kategori")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Tarih")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Tutar")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("GiderKategoriId");

                    b.ToTable("KasaHareketler");
                });

            modelBuilder.Entity("CariErinc.Models.Kullanici", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("KullaniciAdi")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("OlusturulmaTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SifreHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Kullanicilar");
                });

            modelBuilder.Entity("CariErinc.Models.Musteri", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Adres")
                        .HasColumnType("text");

                    b.Property<DateTime>("OlusturulmaTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Soyad")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Telefon")
                        .HasColumnType("text");

                    b.Property<decimal>("ToplamBorc")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Musteriler");
                });

            modelBuilder.Entity("CariErinc.Models.Satis", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Aciklama")
                        .HasColumnType("text");

                    b.Property<bool>("IptalEdildi")
                        .HasColumnType("boolean");

                    b.Property<string>("IptalNedeni")
                        .HasColumnType("text");

                    b.Property<DateTime?>("IptalTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("KismiIade")
                        .HasColumnType("boolean");

                    b.Property<int?>("MusteriId")
                        .HasColumnType("integer");

                    b.Property<int>("OdemeTipi")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Tarih")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("ToplamTutar")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("MusteriId");

                    b.ToTable("Satislar");
                });

            modelBuilder.Entity("CariErinc.Models.SatisDetay", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("AlisBirimFiyati")
                        .HasColumnType("numeric");

                    b.Property<decimal>("BirimFiyat")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<int>("KdvOrani")
                        .HasColumnType("integer");

                    b.Property<decimal>("KdvTutari")
                        .HasColumnType("numeric");

                    b.Property<int>("Miktar")
                        .HasColumnType("integer");

                    b.Property<int>("SatisId")
                        .HasColumnType("integer");

                    b.Property<int>("UrunId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("SatisId");

                    b.HasIndex("UrunId");

                    b.ToTable("SatisDetaylari");
                });

            modelBuilder.Entity("CariErinc.Models.SatisIade", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("IadeTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Neden")
                        .HasColumnType("text");

                    b.Property<int>("SatisId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("SatisId");

                    b.ToTable("SatisIadeler");
                });

            modelBuilder.Entity("CariErinc.Models.SatisIadeDetay", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("IadeMiktar")
                        .HasColumnType("integer");

                    b.Property<decimal>("IadeTutari")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<int>("SatisDetayId")
                        .HasColumnType("integer");

                    b.Property<int>("SatisIadeId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("SatisDetayId");

                    b.HasIndex("SatisIadeId");

                    b.ToTable("SatisIadeDetaylari");
                });

            modelBuilder.Entity("CariErinc.Models.StokHareket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Aciklama")
                        .HasColumnType("text");

                    b.Property<int>("HareketTipi")
                        .HasColumnType("integer");

                    b.Property<int>("Miktar")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Tarih")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UrunId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UrunId");

                    b.ToTable("StokHareketler");
                });

            modelBuilder.Entity("CariErinc.Models.Tedarikci", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Adres")
                        .HasColumnType("text");

                    b.Property<DateTime>("OlusturulmaTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Telefon")
                        .HasColumnType("text");

                    b.Property<decimal>("ToplamBorc")
                        .HasColumnType("numeric");

                    b.Property<string>("YetkiliKisi")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Tedarikciler");
                });

            modelBuilder.Entity("CariErinc.Models.Urun", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<decimal>("AlisFiyati")
                        .HasColumnType("numeric");

                    b.Property<string>("Barkod")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<decimal>("BirimFiyat")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTime>("GuncellenmeTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Kategori")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("KdvOrani")
                        .HasColumnType("integer");

                    b.Property<int>("MinStokUyari")
                        .HasColumnType("integer");

                    b.Property<DateTime>("OlusturulmaTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("SonAlisTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("StokAdedi")
                        .HasColumnType("integer");

                    b.Property<int?>("TedarikciId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TedarikciId");

                    b.ToTable("Urunler");
                });

            modelBuilder.Entity("CariErinc.Models.Veresiye", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Aciklama")
                        .HasColumnType("text");

                    b.Property<int>("MusteriId")
                        .HasColumnType("integer");

                    b.Property<int>("OdenmeDurumu")
                        .HasColumnType("integer");

                    b.Property<int?>("SatisId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Tarih")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Tutar")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("MusteriId");

                    b.HasIndex("SatisId")
                        .IsUnique();

                    b.ToTable("Veresiyeler");
                });

            modelBuilder.Entity("CariErinc.Models.VeresiyeOdeme", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Aciklama")
                        .HasColumnType("text");

                    b.Property<DateTime>("OdemeTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("OdemeTutari")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<int>("VeresiyeId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("VeresiyeId");

                    b.ToTable("VeresiyeOdemeler");
                });

            modelBuilder.Entity("CariErinc.Models.Alis", b =>
                {
                    b.HasOne("CariErinc.Models.Tedarikci", "Tedarikci")
                        .WithMany("Alislar")
                        .HasForeignKey("TedarikciId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tedarikci");
                });

            modelBuilder.Entity("CariErinc.Models.AlisDetay", b =>
                {
                    b.HasOne("CariErinc.Models.Alis", "Alis")
                        .WithMany("AlisDetaylari")
                        .HasForeignKey("AlisId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CariErinc.Models.Urun", "Urun")
                        .WithMany()
                        .HasForeignKey("UrunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Alis");

                    b.Navigation("Urun");
                });

            modelBuilder.Entity("CariErinc.Models.AlisOdeme", b =>
                {
                    b.HasOne("CariErinc.Models.Alis", "Alis")
                        .WithMany("AlisOdemeleri")
                        .HasForeignKey("AlisId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Alis");
                });

            modelBuilder.Entity("CariErinc.Models.KasaHareket", b =>
                {
                    b.HasOne("CariErinc.Models.GiderKategori", "GiderKategori")
                        .WithMany()
                        .HasForeignKey("GiderKategoriId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("GiderKategori");
                });

            modelBuilder.Entity("CariErinc.Models.Satis", b =>
                {
                    b.HasOne("CariErinc.Models.Musteri", "Musteri")
                        .WithMany()
                        .HasForeignKey("MusteriId");

                    b.Navigation("Musteri");
                });

            modelBuilder.Entity("CariErinc.Models.SatisDetay", b =>
                {
                    b.HasOne("CariErinc.Models.Satis", "Satis")
                        .WithMany("SatisDetaylari")
                        .HasForeignKey("SatisId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CariErinc.Models.Urun", "Urun")
                        .WithMany()
                        .HasForeignKey("UrunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Satis");

                    b.Navigation("Urun");
                });

            modelBuilder.Entity("CariErinc.Models.SatisIade", b =>
                {
                    b.HasOne("CariErinc.Models.Satis", "Satis")
                        .WithMany("SatisIadeler")
                        .HasForeignKey("SatisId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Satis");
                });

            modelBuilder.Entity("CariErinc.Models.SatisIadeDetay", b =>
                {
                    b.HasOne("CariErinc.Models.SatisDetay", "SatisDetay")
                        .WithMany()
                        .HasForeignKey("SatisDetayId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CariErinc.Models.SatisIade", "SatisIade")
                        .WithMany("IadeDetaylari")
                        .HasForeignKey("SatisIadeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SatisDetay");

                    b.Navigation("SatisIade");
                });

            modelBuilder.Entity("CariErinc.Models.StokHareket", b =>
                {
                    b.HasOne("CariErinc.Models.Urun", "Urun")
                        .WithMany()
                        .HasForeignKey("UrunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Urun");
                });

            modelBuilder.Entity("CariErinc.Models.Urun", b =>
                {
                    b.HasOne("CariErinc.Models.Tedarikci", "Tedarikci")
                        .WithMany("Urunler")
                        .HasForeignKey("TedarikciId");

                    b.Navigation("Tedarikci");
                });

            modelBuilder.Entity("CariErinc.Models.Veresiye", b =>
                {
                    b.HasOne("CariErinc.Models.Musteri", "Musteri")
                        .WithMany("Veresiyeler")
                        .HasForeignKey("MusteriId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CariErinc.Models.Satis", "Satis")
                        .WithOne("Veresiye")
                        .HasForeignKey("CariErinc.Models.Veresiye", "SatisId");

                    b.Navigation("Musteri");

                    b.Navigation("Satis");
                });

            modelBuilder.Entity("CariErinc.Models.VeresiyeOdeme", b =>
                {
                    b.HasOne("CariErinc.Models.Veresiye", "Veresiye")
                        .WithMany("Odemeler")
                        .HasForeignKey("VeresiyeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Veresiye");
                });

            modelBuilder.Entity("CariErinc.Models.Alis", b =>
                {
                    b.Navigation("AlisDetaylari");

                    b.Navigation("AlisOdemeleri");
                });

            modelBuilder.Entity("CariErinc.Models.Musteri", b =>
                {
                    b.Navigation("Veresiyeler");
                });

            modelBuilder.Entity("CariErinc.Models.Satis", b =>
                {
                    b.Navigation("SatisDetaylari");

                    b.Navigation("SatisIadeler");

                    b.Navigation("Veresiye");
                });

            modelBuilder.Entity("CariErinc.Models.SatisIade", b =>
                {
                    b.Navigation("IadeDetaylari");
                });

            modelBuilder.Entity("CariErinc.Models.Tedarikci", b =>
                {
                    b.Navigation("Alislar");

                    b.Navigation("Urunler");
                });

            modelBuilder.Entity("CariErinc.Models.Veresiye", b =>
                {
                    b.Navigation("Odemeler");
                });
#pragma warning restore 612, 618
        }
    }
}
